# ticketAppender.coffee
FileAppender = require '../file-appender'
moment = require 'moment'

class TicketAppender extends FileAppender
	doAppend: (itineraryResult, callback) ->
		if !itineraryResult.Booking.Tickets?
			return callback null
		updateDate = @dataDate
		appendCSV = @appendCSV
		filePath = @filePath
		fileName = @fileName
		tickets = itineraryResult.Booking.Tickets[0].Ticket
		tickets.forEach (item) ->
			record = []
			record.push item.booking_id[0]
			record.push item.departure_time[0]
			record.push item.passenger_id[0]
			record.push item.booking_segment_id[0]
			record.push item.origin_rcd[0]
			record.push item.destination_rcd[0]
			record.push item.lastname[0]
			record.push item.firstname[0]
			record.push item.gender_type_rcd[0]
			record.push item.title_rcd[0]
			record.push item.title[0]
			record.push item.language_rcd[0]
			record.push item.passenger_type_rcd[0]
			record.push moment(item.date_of_birth[0], "YYYYMMDD HH:mm:ss").format "YYYY/MM/DD HH:mm:ss"
			record.push item.flight_id[0]
			record.push item.airline_rcd[0]
			record.push item.flight_number[0]
			record.push moment(item.departure_date[0], "YYYYMMDD HH:mm:ss").format "YYYY/MM/DD HH:mm:ss"
			record.push item.boarding_class_rcd[0]
			record.push item.booking_class_rcd[0]
			record.push item.record_locator[0]
			record.push item.seat_number[0]
			record.push item.seat_row[0]
			record.push item.seat_column[0]
			record.push item.seat_fee_rcd[0]
			record.push item.currency_rcd[0]
			record.push item.net_total[0]
			record.push item.tax_amount[0]
			record.push item.fare_amount[0]
			record.push item.fare_quote_amount[0]
			record.push item.yq_amount[0]
			record.push item.base_ticketing_fee_amount[0]
			record.push item.ticketing_fee_amount[0]
			record.push item.reservation_fee_amount[0]
			record.push item.commission_amount[0]
			record.push item.commission_percentage[0]
			record.push item.refund_charge[0]
			record.push item.refundable_amount[0]
			record.push item.fare_vat[0]
			record.push item.tax_vat[0]
			record.push item.yq_vat[0]
			record.push item.ticketing_fee_vat[0]
			record.push item.reservation_fee_vat[0]
			record.push item.acct_net_total[0]
			record.push item.acct_tax_amount[0]
			record.push item.acct_fare_amount[0]
			record.push item.acct_yq_amount[0]
			record.push item.acct_ticketing_fee_amount[0]
			record.push item.acct_reservation_fee_amount[0]
			record.push item.acct_commission_amount[0]
			record.push item.acct_refundable_amount[0]
			record.push item.flight_connection_id[0]
			record.push item.od_origin_rcd[0]
			record.push item.od_destination_rcd[0]
			record.push item.prorate_acct_fare_amount[0]
			record.push item.prorate_acct_yq_amount[0]
			record.push item.prorate_sales_fare_amount[0]
			record.push item.prorate_sales_yq_amount[0]
			record.push item.fare_id[0]
			record.push item.fare_code[0]
			record.push moment(item.fare_date_time[0], "YYYYMMDD HH:mm:ss").format "YYYY/MM/DD HH:mm:ss"
			record.push item.accounting_refund_batch[0]
			record.push item.refundable_flag[0]
			record.push item.transferable_fare_flag[0]
			record.push item.unavailable_flag[0]
			record.push item.refund_with_charge_hours[0]
			record.push item.refund_not_possible_hours[0]
			record.push item.e_ticket_flag[0]
			record.push item.standby_flag[0]
			record.push item.exclude_pricing_flag[0]
			record.push item.passenger_check_in_status_rcd[0]
			record.push item.priority_code[0]
			record.push item.agency_code[0]
			record.push item.passenger_status_rcd[0]
			record.push item.ticket_number[0]
			record.push moment(item.ticketing_date_time[0], "YYYYMMDD HH:mm:ss").format "YYYY/MM/DD HH:mm:ss"
			record.push item.ticketing_by[0]
			record.push item.public_fare_amount[0]
			record.push item.document_number[0]
			record.push item.form_of_payment[0]
			record.push item.tour_code[0]
			record.push item.fim_flag[0]
			record.push item.duty_travel_flag[0]
			record.push item.boarding_pass_number[0]
			record.push moment(item.check_in_date_time[0], "YYYYMMDD HH:mm:ss").format "YYYY/MM/DD HH:mm:ss"
			record.push item.check_in_comment[0]
			record.push item.check_in_sequence[0]
			record.push item.group_sequence[0]
			record.push item.unload_by[0]
			record.push moment(item.unload_date_time[0], "YYYYMMDD HH:mm:ss").format "YYYY/MM/DD HH:mm:ss"
			record.push item.unload_comment[0]
			record.push item.number_of_pieces[0]
			record.push item.baggage_weight[0]
			record.push item.piece_allowance[0]
			record.push item.excess_baggage_weight[0]
			record.push item.check_in_baggage_weight[0]
			record.push item.group_baggage_weight[0]
			record.push item.changed_baggage_weight[0]
			record.push item.check_in_user_code[0]
			record.push item.check_in_by[0]
			record.push item.cancel_by[0]
			record.push moment(item.cancel_date_time[0], "YYYYMMDD HH:mm:ss").format "YYYY/MM/DD HH:mm:ss"
			record.push item.create_by[0]
			record.push moment(item.create_date_time[0], "YYYYMMDD HH:mm:ss").format "YYYY/MM/DD HH:mm:ss"
			record.push item.update_by[0]
			record.push moment(item.update_date_time[0], "YYYYMMDD HH:mm:ss").format "YYYY/MM/DD HH:mm:ss"
			record.push item.refund_agency_code[0]
			record.push item.refund_by[0]
			record.push moment(item.refund_date_time[0], "YYYYMMDD HH:mm:ss").format "YYYY/MM/DD HH:mm:ss"
			record.push item.void_by[0]
			record.push moment(item.void_date_time[0], "YYYYMMDD HH:mm:ss").format "YYYY/MM/DD HH:mm:ss"
			record.push moment(item.exchanged_date_time[0], "YYYYMMDD HH:mm:ss").format "YYYY/MM/DD HH:mm:ss"
			record.push item.exchanged_segment_id[0]
			record.push item.onward_airline_rcd[0]
			record.push item.onward_flight_number[0]
			record.push moment(item.onward_departure_date[0], "YYYYMMDD HH:mm:ss").format "YYYY/MM/DD HH:mm:ss"
			record.push item.onward_destination_rcd[0]
			record.push item.onward_booking_class_rcd[0]
			record.push item.restriction_text[0]
			record.push item.endorsement_text[0]
			record.push moment(item.not_valid_before_date[0], "YYYYMMDD HH:mm:ss").format "YYYY/MM/DD HH:mm:ss"
			record.push moment(item.not_valid_after_date[0], "YYYYMMDD HH:mm:ss").format "YYYY/MM/DD HH:mm:ss"
			record.push item.fare_line[0]
			record.push item.check_in_code[0]
			record.push item.present_flag[0]
			record.push item.through_fare_flag[0]
			record.push item.bsp_checked_flag[0]
			record.push item.adm_raised_flag[0]
			record.push item.adm_document[0]
			record.push item.bsp_period[0]
			record.push item.bsp_month[0]
			record.push item.bsp_year[0]
			record.push item.bsp_comment[0]
			record.push item.advanced_seating_flag[0]
			record.push item.it_fare_flag[0]
			record.push item.ticket_id[0]
			record.push item.coupon_number[0]
			record.push item.fare_type_rcd[0]
			record.push item.redemption_points[0]
			record.push item.origin_sequence[0]
			record.push item.destination_sequence[0]
			record.push item.fare_description[0]
			record.push item.fare_note[0]
			record.push item.fare_column[0]
			record.push item.promotion_code[0]
			record.push item.day_of_year[0]
			record.push item.payment_amount[0]
			record.push item.create_name[0]
			record.push item.update_name[0]
			record.push item.approval_flag[0]
			record.push item.group_name[0]
			record.push item.contact_name[0]
			record.push item.contact_email[0]
			record.push item.phone_mobile[0]
			record.push item.phone_home[0]
			record.push item.phone_business[0]
			record.push item.received_from[0]
			record.push item.phone_fax[0]
			record.push item.vendor_rcd[0]
			record.push item.tour_operator_locator[0]
			record.push item.group_count[0]
			record.push item.record_locator_display[0]
			record.push item.e_ticket_status[0]
			record.push item.baggage_count_fee_rcd[0]
			record.push item.baggage_weight_fee_rcd[0]
			record.push item.fee_baggage_weight_kgs[0]
			record.push item.fee_baggage_weight_lbs[0]
			record.push item.fee_baggage_count[0]
			record.push updateDate
			appendCSV filePath, fileName, record, (err) ->
				if err?
					return callback err
		callback null

module.exports = TicketAppender